###############################################################
# Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

name: Push Nuget Packages and Tag

on:
  push:
      paths:
        - 'src/framework/**'
      branches:
        - 'dev'
        - 'release/v*.*.*-RC*'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['7.0']
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Install dependencies
      run: dotnet restore src/framework

    - name: Build
      run: dotnet build src/framework --configuration Release --no-restore

    - name: Push nuget packages
      shell: bash
      run: |
        bash ./scripts/pack_and_push_packages.sh ${{ secrets.NUGET_API_KEY }}

    - name: Get new version
      id: nugetPackageVersion
      shell: bash
      run: |
        current_version=$(./scripts/get_current_version.sh)
        echo "version=$current_version" >> "$GITHUB_OUTPUT"

    - name: Create git tag
      uses: rickstaa/action-create-tag@v1
      with:
        tag: v${{ steps.nugetPackageVersion.outputs.version }}
