###############################################################
# Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

name: Push Nuget Version Update

on:
    push:
        paths:
            - 'src/framework/**'
    pull_request:
        types: [opened, synchronize, reopened]
    workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['7.0']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    
    - name: Check Package Versions
      id: check-version-update
      run: |
        script_output=$(./scripts/check_push_version_update.sh github.event.pull_request.base.ref github.event.pull_request.head.ref)

        if [ -z "$script_output" ]; then
          echo "Expected version updates were made"
        else
          echo "$script_output" > failed_log.txt
          exit 1
        fi

    - name: Push nuget packages
      if: success()
      run: |
        bash ./scripts/pack_and_push_packages.sh nuget secrets.NUGET_API_KEY

    # Create tag for nuget version update